# GitHub Actions for PostGIS
#
# Paul Ramsey <pramsey at cleverelephant dot ca>

name: "CI"
on: [push, pull_request]

jobs:
  linux:

    runs-on: ubuntu-20.04

    env:
      PG_VERSION: 14
      OS_NAME: focal-pgdg

    steps:

    - name: 'Check Out'
      uses: actions/checkout@v2

    - name: 'Install'
      run: |
        curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        sudo add-apt-repository "deb http://apt.postgresql.org/pub/repos/apt/ $OS_NAME main $PG_VERSION"
        sudo apt-get -y install libcurl4-gnutls-dev postgresql-server-dev-$PG_VERSION
        sudo cp ./ci/pg_hba.conf /etc/postgresql/$PG_VERSION/main/pg_hba.conf
        sudo systemctl start postgresql.service

    - name: 'Build & Test'
      run: |
        export PATH=/usr/lib/postgresql/$PG_VERSION/bin/:$PATH
        make
        sudo make install
        PGUSER=postgres make installcheck || (cat regression.diffs && /bin/false)
